### ISSUE TITLE
Scripts to convert raw data into input data for the model

### ISSUE THREAD

**Issue by Pranav-Goel** [rsepulveda911112/HeadlineStanceChecker#1]
Hello,

I really like the paper and the summarizer-based approach! I am sorry if I missed it, but there do not seem to be scripts that go from the data of just the body and headline of articles to summarizer results, and especially the values of features (such as 'cosineSimilarity' 'max_score_in_position' 'overlap') used to create the data files that can be used to train/predict using the provided models. Are there plans to release those data processing scripts? Are there any ready pointers to get the feature values for the body and the headline in order to use the pretrained models on a different news article dataset? 

Thanks!

**Comment by rsepulveda911112** [comment]
Hello

I commit a script to preprocess a new dataset. This script uses TextRank summarizer instead of PLM summarizer because PLM is not available yet.

**Comment by Pranav-Goel** [comment]
Thanks for the script! Just one note - in the README, it appears the description of 'dataset_out' is wrong. This is very helpful!
